#!/usr/bin/env python3
"""Replay app-feature `spel_retro_audio` predictions with Collector visibility gates.

T0032 showed that the Collector app's TypeScript feature path can produce
different labels/confidences than the Python/librosa replay. This script
evaluates a dataset generated by
`build_playing_retro_audio_app_feature_dataset_t0033.js` using the same
review thresholds, recovery gates, and same-label dedupe as the installed app.
It does not retrain, export app JSON, build an APK, or change `studs_live`.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

import replay_playing_retro_audio_t0027 as base
from train_playing_retro_audio import EVAL_DIR


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_DATASET_CSV = (
    REPO_ROOT
    / "data"
    / "audio"
    / "processed"
    / "playing_retro_audio_app_feature_dataset_t0033_2026_06_04_006.csv"
)
DEFAULT_SESSIONS = ["audio_session_2026-06-04_006"]

APP_RACKET_THRESHOLD = 0.0
APP_TABLE_THRESHOLD = 0.0
APP_RECOVERY_RACKET_MIN_CONFIDENCE = 0.8
APP_RECOVERY_TABLE_MIN_CONFIDENCE = 0.54
APP_RECOVERY_RACKET_MIN_SAVED_GAP_MS = 120
APP_RECOVERY_TABLE_MIN_SAVED_GAP_MS = 60

PREDICTIONS_CSV = EVAL_DIR / "playing_retro_audio_t0033_app_feature_predictions.csv"
REPORT_JSON = EVAL_DIR / "playing_retro_audio_t0033_app_feature_replay_report.json"
REPORT_MD = EVAL_DIR / "playing_retro_audio_t0033_app_feature_replay_report.md"


def json_default(value: Any) -> Any:
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def app_prediction_events(
    df: pd.DataFrame,
    prediction_column: str,
    confidence_column: str,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for index, row in df.iterrows():
        label = str(row[prediction_column])
        kind = base.marker_kind(label)
        if not kind:
            continue
        confidence = float(row[confidence_column])
        threshold = APP_RACKET_THRESHOLD if kind == "racket" else APP_TABLE_THRESHOLD
        if confidence < threshold:
            continue

        is_recovery = bool(row.get("is_recovery_candidate", False))
        if is_recovery:
            nearest_saved_gap_ms = row.get("nearest_saved_gap_ms")
            gap = None if pd.isna(nearest_saved_gap_ms) else float(nearest_saved_gap_ms)
            if kind == "racket" and not (
                confidence >= APP_RECOVERY_RACKET_MIN_CONFIDENCE
                and (gap is None or gap >= APP_RECOVERY_RACKET_MIN_SAVED_GAP_MS)
            ):
                continue
            if kind == "table" and not (
                confidence >= APP_RECOVERY_TABLE_MIN_CONFIDENCE
                and (gap is None or gap >= APP_RECOVERY_TABLE_MIN_SAVED_GAP_MS)
            ):
                continue

        rows.append({
            "source_index": int(index),
            "session_id": str(row["session_id"]),
            "event_index": int(row["event_index"]),
            "timestamp_ms": float(row["anchor_ms"]),
            "kind": kind,
            "confidence": confidence,
            "candidate_id": str(row.get("candidate_id") or ""),
            "is_recovery": is_recovery,
        })
    return pd.DataFrame(rows)


def raw_prediction_counts(df: pd.DataFrame, prediction_column: str) -> dict[str, Any]:
    counts = df[prediction_column].fillna("").astype(str).value_counts().to_dict()
    target = df[df[prediction_column].isin(["racket_contact", "table_bounce"])]
    return {
        "all_predictions": {str(key): int(value) for key, value in counts.items()},
        "target_candidate_rows": int(len(target)),
        "target_by_label": {
            str(key): int(value)
            for key, value in target[prediction_column].fillna("").astype(str).value_counts().to_dict().items()
        },
    }


def write_markdown(report: dict[str, Any]) -> None:
    summary = report["marker_replay"]["app_feature_current"]
    lines = [
        "# Playing Retro Audio T0033 App-Feature Replay",
        "",
        "This is a parity replay. It uses Collector-style app features and app visibility gates. No model, APK, `studs_live`, ordinary bounce, or video artifact was changed.",
        "",
        "## Result",
        "",
        f"- Dataset: `{report['dataset_csv']}`",
        f"- Sessions: `{report['sessions']}`",
        f"- Raw app predictions: `{report['raw_prediction_counts']['all_predictions']}`",
        f"- Target candidate rows before app gates/dedupe: `{report['raw_prediction_counts']['target_candidate_rows']}`",
        f"- Editable marker replay: `{summary['true_positive']} TP / {summary['wrong_class']} wrong / {summary['false_positive']} FP / {summary['missed']} missed`",
        f"- Racket/table TP: `{summary['tp_racket']}` / `{summary['tp_table']}`",
        f"- Same-label duplicates removed: `{summary['same_label_duplicates_removed']}`",
        "",
        "## Per Session",
        "",
        "| Session | Predictions | TP | Wrong | FP | Missed | Racket TP | Table TP |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for session_id, item in report["marker_replay"]["per_session"].items():
        lines.append(
            f"| `{session_id}` | {item.get('predictions', 0)} | {item.get('true_positive', 0)} | "
            f"{item.get('wrong_class', 0)} | {item.get('false_positive', 0)} | {item.get('missed', 0)} | "
            f"{item.get('tp_racket', 0)} | {item.get('tp_table', 0)} |"
        )
    lines.extend([
        "",
        "## Outputs",
        "",
        f"- Predictions CSV: `{PREDICTIONS_CSV.as_posix()}`",
        f"- JSON report: `{REPORT_JSON.as_posix()}`",
        "",
    ])
    REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay Collector app-feature playing-retro output.")
    parser.add_argument("--dataset-csv", default=str(DEFAULT_DATASET_CSV))
    parser.add_argument("--session", action="append", default=None)
    parser.add_argument("--prediction-column", default="t0033_app_prediction")
    parser.add_argument("--confidence-column", default="t0033_app_confidence")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    dataset_path = Path(args.dataset_csv)
    if not dataset_path.exists():
        raise SystemExit(f"Missing {dataset_path}; build the T0033 app-feature dataset first.")

    sessions = args.session or DEFAULT_SESSIONS
    dataset = pd.read_csv(dataset_path)
    target = dataset[dataset["session_id"].astype(str).isin(set(sessions))].copy()
    candidate_df = target[target["row_type"].fillna("").astype(str) == "candidate"].copy()
    if candidate_df.empty:
        raise SystemExit("No candidate rows found for requested sessions.")
    if args.prediction_column not in candidate_df.columns:
        raise SystemExit(f"Missing prediction column {args.prediction_column}")
    if args.confidence_column not in candidate_df.columns:
        raise SystemExit(f"Missing confidence column {args.confidence_column}")

    candidate_df["is_recovery_candidate"] = base.recovery_mask(candidate_df)
    candidate_df["nearest_saved_gap_ms"] = base.nearest_saved_gap_by_row(candidate_df)
    events = app_prediction_events(candidate_df, args.prediction_column, args.confidence_column)
    truths = base.truth_rows_for_sessions(sessions)
    summary, per_session_rows = base.evaluate_marker_predictions(
        events,
        truths,
        scope="app_feature_current",
        match_ms=base.REPLAY_MATCH_MS,
        dedupe_ms=base.SAME_LABEL_DEDUPE_MS,
    )

    PREDICTIONS_CSV.parent.mkdir(parents=True, exist_ok=True)
    prediction_columns = [
        "session_id",
        "event_index",
        "wav_filename",
        "candidate_id",
        "anchor_ms",
        "label",
        "row_type",
        "candidate_status",
        "candidate_predicted_kind",
        args.prediction_column,
        args.confidence_column,
        "t0033_app_probability_non_target",
        "t0033_app_probability_racket_contact",
        "t0033_app_probability_table_bounce",
        "source_rule",
        "match_outcome",
        "close_event_bucket",
        "neighbor_sequence",
        "is_recovery_candidate",
        "nearest_saved_gap_ms",
    ]
    candidate_df[[column for column in prediction_columns if column in candidate_df.columns]].to_csv(
        PREDICTIONS_CSV,
        index=False,
    )

    report = {
        "ticket": "T0033",
        "status": "app_feature_parity_replay_only_not_exported",
        "dataset_csv": str(dataset_path),
        "sessions": sessions,
        "candidate_rows": int(len(candidate_df)),
        "truth_rows": int(len(truths)),
        "raw_prediction_counts": raw_prediction_counts(candidate_df, args.prediction_column),
        "app_gates": {
            "racket_threshold": APP_RACKET_THRESHOLD,
            "table_threshold": APP_TABLE_THRESHOLD,
            "recovery_racket_min_confidence": APP_RECOVERY_RACKET_MIN_CONFIDENCE,
            "recovery_table_min_confidence": APP_RECOVERY_TABLE_MIN_CONFIDENCE,
            "recovery_racket_min_saved_gap_ms": APP_RECOVERY_RACKET_MIN_SAVED_GAP_MS,
            "recovery_table_min_saved_gap_ms": APP_RECOVERY_TABLE_MIN_SAVED_GAP_MS,
            "same_label_dedupe_ms": base.SAME_LABEL_DEDUPE_MS,
        },
        "marker_replay": {
            "app_feature_current": summary,
            "per_session": base.per_session_totals(per_session_rows),
        },
        "outputs": {
            "predictions_csv": str(PREDICTIONS_CSV),
            "report_json": str(REPORT_JSON),
            "report_md": str(REPORT_MD),
        },
        "changed_app_artifacts": False,
        "changed_studs_live": False,
        "changed_video_model": False,
    }
    REPORT_JSON.write_text(json.dumps(report, indent=2, default=json_default), encoding="utf-8")
    write_markdown(report)

    print(f"Wrote {PREDICTIONS_CSV}")
    print(f"Wrote {REPORT_JSON}")
    print(f"Wrote {REPORT_MD}")
    print(
        "app_feature_current: pred={pred} tp={tp} wrong={wrong} fp={fp} missed={missed}".format(
            pred=summary["predictions"],
            tp=summary["true_positive"],
            wrong=summary["wrong_class"],
            fp=summary["false_positive"],
            missed=summary["missed"],
        )
    )


if __name__ == "__main__":
    main()
